// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/portfolio/BentoBoard.tsx": () => import("../components/mockups/portfolio/BentoBoard.tsx"),
  "./components/mockups/portfolio/FilterableCards.tsx": () => import("../components/mockups/portfolio/FilterableCards.tsx"),
  "./components/mockups/portfolio/MagazineGrid.tsx": () => import("../components/mockups/portfolio/MagazineGrid.tsx")
};
