// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/brand-themes/Baseline.tsx": () => import("../components/mockups/brand-themes/Baseline.tsx"),
  "./components/mockups/brand-themes/BoutiquePractice.tsx": () => import("../components/mockups/brand-themes/BoutiquePractice.tsx"),
  "./components/mockups/brand-themes/EditorialAuthority.tsx": () => import("../components/mockups/brand-themes/EditorialAuthority.tsx"),
  "./components/mockups/brand-themes/ExecutiveMonochrome.tsx": () => import("../components/mockups/brand-themes/ExecutiveMonochrome.tsx"),
  "./components/mockups/brand-themes/OperatorConsole.tsx": () => import("../components/mockups/brand-themes/OperatorConsole.tsx"),
  "./components/mockups/portfolio/BentoBoard.tsx": () => import("../components/mockups/portfolio/BentoBoard.tsx"),
  "./components/mockups/portfolio/FilterableCards.tsx": () => import("../components/mockups/portfolio/FilterableCards.tsx"),
  "./components/mockups/portfolio/MagazineGrid.tsx": () => import("../components/mockups/portfolio/MagazineGrid.tsx"),
  "./components/mockups/site-counsel/AnnualReportSite.tsx": () => import("../components/mockups/site-counsel/AnnualReportSite.tsx"),
  "./components/mockups/site-counsel/ChambersSite.tsx": () => import("../components/mockups/site-counsel/ChambersSite.tsx"),
  "./components/mockups/site-counsel/CinematicSite.tsx": () => import("../components/mockups/site-counsel/CinematicSite.tsx"),
  "./components/mockups/site-counsel/ContrastSplitBlog.tsx": () => import("../components/mockups/site-counsel/ContrastSplitBlog.tsx"),
  "./components/mockups/site-counsel/ContrastSplitPortfolio.tsx": () => import("../components/mockups/site-counsel/ContrastSplitPortfolio.tsx"),
  "./components/mockups/site-counsel/ContrastSplitPost.tsx": () => import("../components/mockups/site-counsel/ContrastSplitPost.tsx"),
  "./components/mockups/site-counsel/ContrastSplitProjects.tsx": () => import("../components/mockups/site-counsel/ContrastSplitProjects.tsx"),
  "./components/mockups/site-counsel/ContrastSplitSite.tsx": () => import("../components/mockups/site-counsel/ContrastSplitSite.tsx"),
  "./components/mockups/site-counsel/InkFoilSite.tsx": () => import("../components/mockups/site-counsel/InkFoilSite.tsx"),
  "./components/mockups/site-counsel/LetterheadSite.tsx": () => import("../components/mockups/site-counsel/LetterheadSite.tsx"),
  "./components/mockups/site-counsel/MinimalSite.tsx": () => import("../components/mockups/site-counsel/MinimalSite.tsx"),
  "./components/mockups/brand-directions/OperatingSystem.tsx": () => import("../components/mockups/brand-directions/OperatingSystem.tsx"),
  "./components/mockups/brand-directions/SeniorCounsel.tsx": () => import("../components/mockups/brand-directions/SeniorCounsel.tsx"),
  "./components/mockups/brand-directions/ThePractice.tsx": () => import("../components/mockups/brand-directions/ThePractice.tsx")
};
