// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/brand-themes/Baseline.tsx": () => import("../components/mockups/brand-themes/Baseline.tsx"),
  "./components/mockups/brand-themes/BoutiquePractice.tsx": () => import("../components/mockups/brand-themes/BoutiquePractice.tsx"),
  "./components/mockups/brand-themes/EditorialAuthority.tsx": () => import("../components/mockups/brand-themes/EditorialAuthority.tsx"),
  "./components/mockups/brand-themes/ExecutiveMonochrome.tsx": () => import("../components/mockups/brand-themes/ExecutiveMonochrome.tsx"),
  "./components/mockups/brand-themes/OperatorConsole.tsx": () => import("../components/mockups/brand-themes/OperatorConsole.tsx"),
  "./components/mockups/portfolio/BentoBoard.tsx": () => import("../components/mockups/portfolio/BentoBoard.tsx"),
  "./components/mockups/portfolio/FilterableCards.tsx": () => import("../components/mockups/portfolio/FilterableCards.tsx"),
  "./components/mockups/portfolio/MagazineGrid.tsx": () => import("../components/mockups/portfolio/MagazineGrid.tsx")
};
